---
- name: When_Condition example
  hosts: appgroup
  gather_facts: False

  tasks:
  - name: Apache installation
    yum: name={{ package }}  state=latest

  - name: tree installation
    yum: name={{ software }}  state=latest




Note: 

ansible-playbook extra_vars.yml --extra-vars "package=wget" --extra-vars "software=zip"
