---
- name: When_Condition example
  hosts: all
  become: True
  gather_facts: True

  tasks:
  - name: Apache Uninstall
    yum: name=httpd state=absent

  - name: Apapche iNstallation on Ubuntu
    apt: name=apache2 state=latest
    when: ansible_distribution == 'Ubuntu'
